environment:
  matrix:
  - channel: stable
  - channel: beta
  - channel: nightly
matrix:
  allow_failures:
  - channel: nightly
platform:
- x86
- x64
install:
- ps: |
    $target = If ($env:platform -eq "x64") { "x86_64-pc-windows-msvc" } Else { "i686-pc-windows-msvc" }
    $installer = ((New-Object Net.WebClient).DownloadString("https://static.rust-lang.org/dist/channel-rust-${env:channel}").Split("`n") | findstr /L "${target}.exe" )
    Start-FileDownload "https://static.rust-lang.org/dist/${installer}" -FileName rust_installer.exe
- rust_installer.exe /VERYSILENT /NORESTART /DIR="%PROGRAMFILES%\Rust"
- SET PATH=%PATH%;%PROGRAMFILES%\Rust\bin
- rustc -vV
- cargo -vV
build_script:
- cargo build --verbose
test_script:
- cargo test --verbose
- cargo bench --verbose
- cargo doc --verbose
- cargo run -q --release --bin roboime-next-cli -- --help
